# Change these first
owner: sulstice # Your GitHub organization or username, where this repository lives
repo: uptime-zinc-db # The name of this repository

sites:
  - name: Zinc 15
    url: https://zinc15.docking.org
  - name: Zinc 20
    url: https://zinc20.docking.org
  - name: PubChem
    url: https://pubchem.ncbi.nlm.nih.gov
  - name: NIST Chemistry Webhook
    url: https://webbook.nist.gov/chemistry/
  - name: Chem Exper
    url: http://www.chemexper.com/
  - name: NMR Shift Database
    url: https://nmrshiftdb.nmr.uni-koeln.de/
  - name: Drug Bank
    url: https://go.drugbank.com/releases/latest
  - name: Binding Database
    url: http://www.bindingdb.org/bind/index.jsp
  - name: Spectral Database for Organic Compounds
    url: https://sdbs.db.aist.go.jp/sdbs/cgi-bin/cre_index.cgi?lang=eng
  - name: Sider
    url: http://sideeffects.embl.de/download/
  - name: ChemSpider
    url: http://www.chemspider.com/Default.aspx
  - name: Stitch
    url: http://stitch.embl.de/cgi/download.pl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://sulstice.github.io/uptime-zinc-db/
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Zinc Database Statuses
  introTitle: "Website Status of the Zinc DB"
