# Change these first
owner: sulstice # Your GitHub organization or username, where this repository lives
repo: uptime-zinc-db # The name of this repository

sites:
  - name: Zinc 15
    url: https://zinc15.docking.org
  - name: Zinc 20
    url: https://zinc20.docking.org
  - name: PubChem
    url: https://pubchem.ncbi.nlm.nih.gov

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://sulstice.github.io/uptime-zinc-db/
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Zinc Database Statuses
  introTitle: "Website Status of the Zinc DB"
